services:
  postgres:
    image: postgres:latest
    container_name: DecissionTreeDB
    environment:
      POSTGRES_USER: admin     # Replace with your desired username
      POSTGRES_PASSWORD: Test@1234 # Replace with your desired password
      POSTGRES_DB: DecissionTree       # Replace with your desired database name
    ports:
      - "5432:5432"                    # Maps container's port 5432 to host's port 5432
    volumes:
      - decissiontree_postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  decissiontree_postgres_data:
    driver: local
